version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    container_name: todolist_db
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
      PG_DB: todolist_api_development
    ports:
      - "5959:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
