---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/boards":
    post:
      summary: Creates a board
      tags:
      - Boards
      parameters: []
      responses:
        '200':
          description: board created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
              required:
              - title
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
