---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/boards":
    post:
      summary: Creates a board
      tags:
      - Boards
      parameters: []
      responses:
        '200':
          description: board created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/BoardCreated"
        '400':
          description: bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorsObject"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
              required:
              - title
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    BoardCreated:
      type: object
      properties:
        board:
          type: object
          properties:
            id:
              type: integer
            title:
              type: string
            description:
              type: string
    ErrorsObject:
      type: object
      properties:
        status:
          type: integer
        errors:
          type: object
